// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcnmGp-3Q2_S4Mi1LdY_SR0yBLoY7Pig8',
    appId: '1:46051006832:web:e1e6edc0f2f3fcad8997b5',
    messagingSenderId: '46051006832',
    projectId: 'anees-app',
    authDomain: 'anees-app.firebaseapp.com',
    storageBucket: 'anees-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_SwKQ_lD2Rru87bzpU3SCbWOhvODZRw',
    appId: '1:46051006832:android:7696fb62698149708997b5',
    messagingSenderId: '46051006832',
    projectId: 'anees-app',
    storageBucket: 'anees-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGwcQVwkMiBcXLr2CKnca5HtLJToEbso',
    appId: '1:46051006832:ios:1e67649b58a36c318997b5',
    messagingSenderId: '46051006832',
    projectId: 'anees-app',
    storageBucket: 'anees-app.firebasestorage.app',
    iosBundleId: 'com.example.aneesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfGwcQVwkMiBcXLr2CKnca5HtLJToEbso',
    appId: '1:46051006832:ios:1e67649b58a36c318997b5',
    messagingSenderId: '46051006832',
    projectId: 'anees-app',
    storageBucket: 'anees-app.firebasestorage.app',
    iosBundleId: 'com.example.aneesApp',
  );
}
